import type { Metadata } from "next";
import { Cairo, DM_Sans } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
// import { ReduxProvider } from "@/lib/redux/provider";
import "../globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <NextIntlClientProvider>
        <body className={`${dmSans.variable} ${cairo.variable} antialiased`}>
          {/* <ReduxProvider> */}
          {children}
          {/* </ReduxProvider> */}
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
